Vagrant.configure("2") do |config|
	config.vm.define "qa" do  |qa|
		qa.vm.box = "ubuntu/precise64"
		qa.vm.network "private_network", ip: "192.168.33.11"
		qa.vm.hostname = "qa"
		qa.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "qa"]
			vb.memory= "1024"
		end		
	end

	config.vm.define "prod" do  |prod|
		prod.vm.box = "ubuntu/precise64"
		prod.vm.network "private_network", ip: "192.168.33.12"
		prod.vm.hostname = "prod"
		prod.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "prod"]
			vb.memory= "1024"
		end		
	end

	config.vm.define "control" do  |control|
		control.vm.box = "ubuntu/precise64"
		control.vm.synced_folder ".","/vagrant", type: "nfs"
		control.vm.network "private_network", ip: "192.168.33.10"
		control.vm.hostname = "control"
		control.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "control"]
			vb.memory= "1024"
		end
		control.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update -y
			sudo apt-get install software-properties-common -y
			sudo apt-add-repository ppa:ansible/ansible -y
			sudo apt-get update -y
			sudo apt-get install ansible -y
		SHELL
	end
	
end
